
name: css & HTML5 Validator
  
on: 
    push: 
        branches: ['*']
    pull_request:
        branches: ['*']

permissions: read-all

jobs:
    build_test:
        runs-on: ubuntu-latest

        steps:
            - name: 'DEBUG: show filesystem 1'
              run: ls -al
            - name: âœ” HTML5 Validator
              uses: Cyb3r-Jak3/html5validator-action@v0.6.1
              with:
                root: src/
                css: true
            - name: 'DEBUG: show filesystem 2'
              run: ls -al

  